swagswap/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#Dajaxice
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('imageswap.views',
    url(r'^$', 'home'),
    url(r'^edit/(?P<image_id>\w+)/$', 'home'),
    url(r'^uploadheadshot/$', 'upload_headshot'),
    url(r'^uploadstyle/$', 'upload_style'),
    url(r'^login/$', 'log_in'),
    url(r'^logout/$', 'log_out'),
    url(r'^register/$', 'register'),
    url(r'^account/$', 'account'),
    url(r'^polls/$', 'polls'),
    url(r'^polls/(?P<pk>\d+)/$','poll'),
    url(r'^createpoll/$', 'createpoll'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    # Examples:
    # url(r'^$', 'swagswap.views.home', name='home'),
    # url(r'^swagswap/', include('swagswap.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

imageswap/models.py
from django.db import models
from django.contrib.auth.models import User
from swagswap.settings import MEDIA_ROOT

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    last_used_headshot = models.ForeignKey('Headshot', blank=True, null=True)
    votes = models.IntegerField(default=0)
    credibility = models.IntegerField(default=0)

    def __unicode__(self):
        return self.user.username

class Headshot(models.Model):
    image = models.ImageField(upload_to="headshots/")
    user = models.ForeignKey(UserProfile)
    date = models.DateTimeField()

    def __unicode__(self):
        return self.user.user.username

class Style(models.Model):
    image = models.ImageField(upload_to="styles/")
    caption = models.CharField(max_length=50)
    # date = models.DateTimeField()
    # user = models.ForeignKey(UserProfile)

    def __unicode__(self):
        return self.caption

class Image(models.Model):
    date = models.DateTimeField()
    user = models.ForeignKey(UserProfile)
    image = models.ImageField(upload_to="images/")
    style = models.ForeignKey(Style, related_name="style")
    headshot = models.ForeignKey(Headshot, related_name="headshot")
    x_offset = models.IntegerField()
    y_offset = models.IntegerField()
    style_width = models.IntegerField()
    style_height = models.IntegerField()

    def __unicode__(self):
        return self.image.name

    def get_id_as_hex(self):
        return hex(self.id)[2:-1]

class Poll(models.Model):
    user = models.ForeignKey(UserProfile)
    date = models.DateTimeField()
    question = models.CharField(max_length=200)
    is_private = models.BooleanField()
    images = models.ManyToManyField(Image, through='Choice')
    users_voted = models.ManyToManyField(UserProfile, related_name="users_voted", blank=True, null=True)

    def __unicode__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    image = models.ForeignKey(Image)
    votes = models.IntegerField()
    
    def __unicode__(self):
        return self.poll.question

imageswap/forms.py
from django import forms
from captcha.fields import ReCaptchaField

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3)
    password = forms.CharField(max_length=32, min_length=5, widget=forms.PasswordInput)
    captcha = ReCaptchaField()

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3)
    password = forms.CharField(max_length=32, min_length=5, widget=forms.PasswordInput)

class CreatePollQuestionForm(forms.Form):
	question = forms.CharField(max_length=200, label='Poll Question', initial="Write your question...")
 	

class CreatePollPrivateForm(forms.Form):
 	private = forms.BooleanField(initial=False,required=False,label='Would you like this poll to be private?')

imageswap/views.py
import Image as PIL
import os, uuid
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login
from swagswap.settings import MEDIA_ROOT
from imageswap.models import UserProfile, Headshot, Style, Image, Poll, Choice
from imageswap.forms import RegisterForm, LoginForm, CreatePollQuestionForm, CreatePollPrivateForm


def home(request, image_id=None):
    #Gets a completed image for editing if a image id is entered
    headshot = None
    if (image_id):
        image = Image.objects.get(pk=int(image_id, 16))
    else:
        image = None
        #Gets the last used headshot of the user if they have one
        if request.user.is_authenticated() and request.user.get_profile().last_used_headshot != None:
            headshot = request.user.get_profile().last_used_headshot

    #Gets style objects
    styles = Style.objects.all()#.order_by('-date')

    if request.user.is_authenticated():
        user_headshots = Headshot.objects.filter(user=request.user.get_profile()).order_by('-date')
    else:
        user_headshots = None

    return render_to_response('imageswap/home.html', 
                              {'loginForm': LoginForm,
                               'styles': styles,
                               'headshot': headshot,
                               'image': image,
                               'userHeadshots': user_headshots},
                              context_instance=RequestContext(request))

@login_required
def upload_headshot(request):
    CONTENT_TYPES = ['image']
    ALLOWED_EXTENSIONS = ['.jpeg', '.jpg', '.jpe', '.png']
    EXTENSIONS_NOT_CONVERTED = ['.jpeg', '.jpg', '.jpe']
    MAX_UPLOAD_SIZE = 5242880 #5mb

    if request.method == 'POST':
        image = request.FILES['uploaded-headshot']  
        extension = os.path.splitext(image.name)[1]
        content_type = image.content_type.split('/')[0]
        #Check to see if image is appropriate for saving
        if extension in ALLOWED_EXTENSIONS and image._size <= MAX_UPLOAD_SIZE and content_type in CONTENT_TYPES:
            #Create required filenames for the new image
            uid = str(uuid.uuid4())[:15]
            filename = uid + "_swagswap" + extension
            relative_filename = os.path.join('headshots', filename)
            absolute_filename = os.path.join(MEDIA_ROOT, relative_filename)

            #Save the image on the file system
            destination = open(absolute_filename, 'wb+')
            for chunk in image:
                destination.write(chunk)
            destination.close()

            #Crop sides of images that are not a portrait
            cropped_image = PIL.open(absolute_filename, 'r')
            if (float(cropped_image.size[1]) / cropped_image.size[0]) < 1.25:
                desired_width = (cropped_image.size[1] / 1.33)
                width_difference = cropped_image.size[0] - desired_width
                cropped_image.crop((int(width_difference/2), 0, int(width_difference/2 + desired_width), cropped_image.size[1])).save(absolute_filename)

            #Convert images that made it through that aren't jpegs, to jpegs
            if extension not in EXTENSIONS_NOT_CONVERTED:               
                image_to_be_converted = PIL.open(absolute_filename, 'r')
                to_be_deleted = absolute_filename
                extension = '.jpeg'
                filename = uid + "_swagswap" + extension
                relative_filename = os.path.join('headshots', filename)
                absolute_filename = os.path.join(MEDIA_ROOT, relative_filename)
                image_to_be_converted.save(absolute_filename)
                #os.remove(to_be_deleted)

            
            #Save image in database
            user_profile = request.user.get_profile() 
            new_headshot = Headshot(image=relative_filename,
                                    user=user_profile,
                                    date=datetime.now())
            new_headshot.save()
            #Set the last used headshot for the user to the new one
            user_profile.last_used_headshot = new_headshot
            user_profile.save()

    return HttpResponseRedirect(reverse('imageswap.views.home', args=()))

@login_required
def upload_style(request):
    CONTENT_TYPES = ['image']
    ALLOWED_EXTENSIONS = ['.png']
    MAX_UPLOAD_SIZE = 5242880 #5mb

    if request.method == 'POST':
        image = request.FILES['uploaded-style']  
        extension = os.path.splitext(image.name)[1]
        content_type = image.content_type.split('/')[0]
        #Check to see if image is appropriate for saving
        if extension in ALLOWED_EXTENSIONS and image._size <= MAX_UPLOAD_SIZE and content_type in CONTENT_TYPES:
            #Create required filenames for the new image
            uid = str(uuid.uuid4())[:15]
            filename = uid + "_swagswap" + extension
            relative_filename = os.path.join('styles', filename)
            absolute_filename = os.path.join(MEDIA_ROOT, relative_filename)

            #Save the image on the file system
            destination = open(absolute_filename, 'wb+')
            for chunk in image:
                destination.write(chunk)
            destination.close()
            
            #Save image in database
            new_style = Style(image=relative_filename,caption="hair")
            new_style.save()

    return HttpResponseRedirect(reverse('imageswap.views.home', args=()))

def log_in(request):
    return render_to_response('imageswap/login.html',
                              {'loginForm': LoginForm},
                              context_instance=RequestContext(request))

def log_out(request):
    logout(request);
    return HttpResponseRedirect(reverse('imageswap.views.home', args=()))

def register(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            try:
                old_user = User.objects.get(username=form.cleaned_data['username'])
            except User.DoesNotExist:
                #new_user = User(username=form.cleaned_data['username'],
                #                password=form.cleaned_data['password'])
                new_user = User.objects.create_user(form.cleaned_data['username'], '', form.cleaned_data['password'])
                new_user.set_password(form.cleaned_data['password'])
                new_user.save()
                UserProfile.objects.create(user=new_user)

                #log new user in
                user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
                if user is not None and user.is_active:
                    login(request, user)

                return HttpResponseRedirect(reverse('imageswap.views.home', args=()))
    
    return render_to_response('imageswap/register.html', 
                              {'form': form,
                              'loginForm': LoginForm},
                              context_instance=RequestContext(request))

@login_required
def account(request):
    polls = Poll.objects.filter(user=request.user.get_profile()).order_by('-date')
    #extra_polls = 5 - polls.count
    images = Image.objects.filter(user=request.user.get_profile()).order_by('-date')
    return render_to_response('imageswap/account.html',
                              {'polls': polls,
                               #'extra_polls': extra_polls,
                              'images': images},
                              context_instance=RequestContext(request))

def polls(request):
  display_num = 3 #the number of polls to display on a page
  older_button = True #if the older button will be showed
  polls = Poll.objects.filter(is_private=False).order_by('-date')

  #hide back button
  if len(polls) <= display_num:
    older_button = False

  #create JSON with the each poll, and the number of empty slots to fill 
  polls = polls[:display_num]
  polls_set = []
  for poll in polls:
    polls_set.append({'poll':poll,
      'remainder': 'banana'})


  display_num -= 1


  

  return render_to_response('imageswap/polls.html',{
                              'polls': polls,
                              'loginForm': LoginForm,
                              'display_num':display_num,
                              'back':older_button,
                 
                              },context_instance = RequestContext(request))



def poll(request, pk):
  #get choices and poll to display
  choices = Choice.objects.filter(poll=pk)
  poll = Poll.objects.get(pk=pk)

  return render_to_response('imageswap/poll.html',
                            {'choices':choices,
                             'poll':poll,
                             'loginForm': LoginForm},
                            context_instance = RequestContext(request))

@login_required
def createpoll(request):
  #get all the user images to choose from
  images = Image.objects.filter(user=request.user.get_profile()).order_by('-date')



  return render_to_response('imageswap/createpoll.html',
                             {'images':images,
                             'CreatePollQuestionForm':CreatePollQuestionForm,
                             'CreatePollPrivateForm':CreatePollPrivateForm},
                             context_instance = RequestContext(request))

templates/imageswap/account.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/account.css">
{% endblock %}

{% block page-js %}
<script type="text/javascript" src="{{ STATIC_URL }}js/account.js"></script>
{% endblock %}

{% block content %}
	<div id="selectors">
		<div id="polls-selector" class="selected">Polls ({{ polls.count }})</div>
		<div id="images-selector" class="not-selected">Images (<span id="image-count">{{ images.count }}</span>)</div>
	</div>

	<div id="account-polls" class="unhidden-account">
		{% for poll in polls %}
			<div class="polls-curr dark-background-border" value="{{poll.id}}">
				<div class="polls-data">
				<p class="polls-user">from {{poll.user.user.username}}</p>
				<a class="polls-question" href="{% url imageswap.views.poll poll.id %}">{{poll.question}} </a>
				</div>
				<div class="polls-images">
					{% for image in poll.images.all %}				
						<img class="polls-image light-background-border" src="{{image.image.url}}"/>
					{% endfor %}
					{% for i in extra_polls %}						
						<img class="polls-image" src=""/>						
					{% endfor %}
				</div>
			</div>
		{% endfor %}
	</div>
	<!-- <div id="account-polls" class="unhidden-account light-background-border">
		{% for poll in polls %}
			<div class="poll-container dark-background-border">
				<div class="poll-question">{{ poll.question }}</div>
				<div class="poll-choices-container">
					{% for choice in poll.images.all %}
						<div>{{ choice.votes }}</div>
						<div class="poll-choice">
							<img class="poll-choice-image" src="{{ choice.image.url }}"/>
							<div class="results-bar" style="height:{{ choice.votes }}px;"></div>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endfor %}
	</div> -->
	<div id="account-images" class="hidden dark-background-border">
		{% for image in images %}
			<div class="account-image-container">
				<img id="account-image-{{ image.id }}" class="account-image" src="{{ image.image.url }}"/>
				<a href="{% url imageswap.views.home image.get_id_as_hex %}">
					<img class="edit-image-image" src="{{ MEDIA_URL}}stylingimages/edit20x20.png"/>
		    	</a>
				<img class="delete-image-image" src="{{ MEDIA_URL}}stylingimages/delete20x20.png"
					 onclick="Dajaxice.imageswap.delete_image
		    					(delete_image_callback, {'image_id':$(this).prev().prev().attr('id').split('-').pop()})"/>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/imageswap/createpoll.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/createpoll.css"/>
{% endblock %}

{% block page-js %}
<script type="text/javascript">
	var blankURL = "{{MEDIA_URL}}headshots/blank.jpg";
    var pollURL = "{% url imageswap.views.polls %}"
</script>
<script type="text/javascript" src="{{ STATIC_URL }}js/createpoll.js"></script>
{% endblock %}


{% block content %}
<div id="createpoll" class="light-background-border">
    
    

    <div id="createpoll-pollimages" class="dark-background-border">
        <div id="createpoll-title"> {{ CreatePollQuestionForm.as_p }} </div>
        <input type="image" class="createpoll-image light-background-border" src="{{MEDIA_URL}}headshots/blank.jpg" value="-1"/>
        <input type="image" class="createpoll-image light-background-border" src="{{MEDIA_URL}}headshots/blank.jpg" value="-1"/>
        <input type="image" class="createpoll-image light-background-border" src="{{MEDIA_URL}}headshots/blank.jpg" value="-1"/>
        <input type="image" class="createpoll-image light-background-border" src="{{MEDIA_URL}}headshots/blank.jpg" value="-1"/>
        <input type="image" class="createpoll-image light-background-border" src="{{MEDIA_URL}}headshots/blank.jpg" value="-1"/>
    </div>


    <div id="createpoll-data">
    
        {{ CreatePollPrivateForm.as_p }}
        


        <p id="createpoll-instruction">Click an images below to add it to the poll</p>




        <div id="createpoll-userimages"> 


            {% for image in images %}
            <input type="image" class="createpoll-userimage light-background-border" src="{{image.image.url}}" value="{{image.pk}}"/>
            {% endfor %}
        </div>
        <button id="make-poll" onClick="Dajaxice.imageswap.create_poll
                                                        (createpoll_callback, 
                                                        {'question':$('#id_question').val(),
                                                         'private':$('#id_private').prop('checked'),
                                                         'images':{
                                                                'image0':$('.createpoll-image').eq(0).attr('value'),
                                                                'image1':$('.createpoll-image').eq(1).attr('value'),
                                                                'image2':$('.createpoll-image').eq(2).attr('value'),
                                                                'image3':$('.createpoll-image').eq(3).attr('value'),
                                                                'image4':$('.createpoll-image').eq(4).attr('value')}
                                                        })">Make Poll</button>


        <div id="createpoll-error"></div>
    </div>
</div>
{% endblock %}

templates/imageswap/home.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}fancybox/jquery.fancybox.css?v=2.1.4">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/home.css">
{% endblock %}

{% block page-js %}
<script type="text/javascript" src="{{STATIC_URL}}fancybox/jquery.fancybox.pack.js?v=2.1.4"></script>
{% if image != None %}
	<script type="text/javascript">	
		var styleURL = "{{ image.style.image.url }}";
		var styleID = "{{ image.style.id }}";
		var x_offset = "{{ image.x_offset }}";
		var y_offset = "{{ image.y_offset }}";
		var headshot_width = "{{ image.headshot.image.width }}";
		var headshot_height = "{{ image.headshot.image.height }}";
		var style_width = "{{ image.style_width }}";
		var style_height = "{{ image.style_height }}";	
	</script>
{% endif %}
<script type="text/javascript" src="{{ STATIC_URL }}js/home.js"></script>
{% endblock %}

{% block content %}
	<div id="home-options" class="dark-background-border">
		{% if user.is_authenticated %}
		<div id="save-button" class="home-option">Save Image</div>
    	<form id="upload-headshot-form" enctype="multipart/form-data" action="{% url imageswap.views.upload_headshot %}" method="POST">{% csrf_token %}
    		<input id="upload-headshot" class="hidden" type="file" name="uploaded-headshot"/>
    		<div id="upload-headshot-button" class="home-option">Upload Headshot</div>
    	</form>
   		<a href="#headshots-container" class="fancybox home-option">Choose Headshot</a>
		<div id="headshots-container" class="hidden">
		{% for userHeadshot in userHeadshots %}
			<input type="image" class="user-headshots" src="{{ userHeadshot.image.url }}" value="{{ userHeadshot.id }}"/>
		{% endfor %}
		</div>
		{% else %}
		<span class="not-logged-in-message">Please sign in to access more features.</span>
		{% endif %}
	</div>
	
	

	<div id="workspace" class="light-background-border">
		{% if image != None %}
			<input type="image" id="headshot" src="{{ image.headshot.image.url }}" value="{{ image.headshot.id }}"/>
		{% elif headshot != None %}
			<input type="image" id="headshot" src="{{ headshot.image.url }}" value="{{ headshot.id }}"/>
		{% else %}
			<input type="image" id="headshot" src="{{ MEDIA_URL}}headshots/blank.jpg" value="0"/>
		{% endif %}
		<!-- <div id="active-style-container"></div> -->
	</div>

	<div id="style-options" class="dark-background-border">
		{% if user.is_authenticated %}
		<form id="upload-style-form" enctype="multipart/form-data" action="{% url imageswap.views.upload_style %}" method="POST">{% csrf_token %}
    		<input id="upload-style" class="hidden" type="file" name="uploaded-style"/>
    		<div id="upload-style-button" class="home-option">Upload Style</div>
    	</form>
    	{% else %}
    	<span class="not-logged-in-message">Sign In.</span>
    	{% endif %}
	</div>
	<div id="style-container" class="light-background-border">
		{% for style in styles %}
			<input type="image" class="style" src="{{ style.image.url }}" value="{{ style.id }}"/>
		{% endfor %}
	</div>
{% endblock %}

templates/imageswap/login.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/login.css">
{% endblock %}

{% block content %}
<div id="login-message" class="light-background-border">You need to login to access this page.</div>
{% endblock %}

templates/imageswap/poll.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/poll.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bar.css">
{% endblock %}

{% block page-js %}
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/poll.js"></script>
{% endblock %}

{% block content %}
	<div id="poll-container" class="dark-background-border">


	
	
	<div id="poll-data">   
		<span id="userdate">{{poll.user}} - {{poll.date}}</span>
		<span id="poll-question">{{poll.question}}</span>
		
	</div>


		<div id="poll-options">
			{% for choice in choices %}

			   
			    	<div class = "poll-option light-background-border">
					    <img class="poll-image" 				    	
					    	 src="{{ choice.image.image.url }}" 
					    	 onclick="Dajaxice.imageswap.vote(vote_callback,{'choicepk':  {{choice.pk}}  })">
					    </img>
					    	
					    <div id="choice{{choice.pk}}" class="poll-votes" value="{{choice.votes}}">{{choice.votes}} </div>
					    
					    <div class="progressbar" data-perc="25">					
							<div class="bar color3"><span class="choice" > </span><span></span></div>
							<div class="label"><span></span></div>
						</div>
					</div>

			

				<!-- <span class="choice" id="choice{{choice.pk}}"> {{choice.votes}}</span> -->

				
			{% endfor %}
		</div>


		
	</div>
<div id="poll-error"></div>





{% endblock %}

templates/imageswap/polls.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/polls.css">
{% endblock %}

{% block page-js %}
<script type="text/javascript" src="{{STATIC_URL}}js/polls.js"></script>
{% endblock %}

{% block content %}



	<table id="polls-table">

		<td class="polls-button-col">
			<div >

			<img id="polls-newer" class="polls-button" 
					src=" {{ MEDIA_URL}}stylingimages/newer.png"
					onClick="Dajaxice.imageswap.polls_set( nextpoll_callback,
											 {
				    							'newest':  $('.polls-curr').eq(0).attr('value'),
				    							'back':  false,
				    							'display_num':  {{display_num}},
				    							'url':'{% url imageswap.views.polls %}'
		    					  			})" />
		    </div>
		</td>
		<td>

	

			<div id="polls-currset">
			{% for poll in polls %}
			
				<div class="polls-curr dark-background-border" value="{{poll.pk}}">
					<div class="polls-data">
					<p class="polls-user">from {{poll.user}}</p>
					<a class="polls-question" href="{% url imageswap.views.poll poll.pk %}">{{poll.question}} {{poll.remainder}}</a>
					</div>

				
						
						
				

					<div class="polls-images">
						{% for image in poll.images.all %}
				
							<img class="polls-image light-background-border" src="{{image.image.url}}"/>
					


						{% endfor %}


						{% for i in poll.remainder %}
							<h1> BANANA </h1>
							<img class="polls-image" src="none"/>
						
						{% endfor %}
					</div>


					



				</div>
		{% endfor %}
		</div>
	</td>
	<td class="polls-button-col">

		<div >
			{% if back %}
		<img id ="polls-older" class="polls-button" 
				src="{{ MEDIA_URL}}stylingimages/older.png"
				onClick="Dajaxice.imageswap.polls_set( 
										nextpoll_callback ,{
			    							'newest':  $('.polls-curr').eq(0).attr('value'),
			    							'back':  true,
			    							'display_num':  {{display_num}},
			    							'url':'{% url imageswap.views.polls %}'
	    					  			})"/>
	    	{% endif %}
	    </div>
	</td>

	
	
		


</div>

</table>
{% endblock %}

templates/imageswap/register.html
{% extends "base.html" %}

{% block page-css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/register.css">
{% endblock %}

{% block content %}
    <div id="form-container">
        <form id="register-form" class="light-background-border" action="{% url imageswap.views.register %}" method="post">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <button id="register-button" class="force-dark" type="submit">Register</button>
        </form>
    </div>
{% endblock %}